## IMPORTING LIBRARIES

In [1]:
import numpy as np

## QUESTION 1

In [2]:
inp_array = np.random.rand(10001)

def my_cumsum(end):
    cumsum = 0
    for i in range(end+1):
        cumsum = cumsum + inp_array[i]

    return cumsum

k = [100,1500,2000,2500,5000,7500,10000]

for k_val in k:
    temp = my_cumsum(k_val) - my_cumsum(k_val-1)
    print("Roundoff error is :",abs(temp - inp_array[k_val]))

Roundoff error is : 7.771561172376096e-16
Roundoff error is : 3.064215547965432e-14
Roundoff error is : 2.9976021664879227e-14
Roundoff error is : 2.942091015256665e-14
Roundoff error is : 2.0516921495072893e-13
Roundoff error is : 2.2615243011614439e-13
Roundoff error is : 2.1316282072803006e-13


### We know that the difference between cummulative sum of k numbers and cummulative sum of k-1 numbers is the array value at kth index .When check the difference between array value at kth index and the difference between cummulative sum , we expect the answer to be 0 . Which is not the case in the output.

### This is due to accumulation of round off errors

## QUESTION 2

In [3]:
# QUESTION 2

x = 0.0
while x <= 2.0 :
    print(x)
    x = x + 0.1

0.0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6
0.7
0.7999999999999999
0.8999999999999999
0.9999999999999999
1.0999999999999999
1.2
1.3
1.4000000000000001
1.5000000000000002
1.6000000000000003
1.7000000000000004
1.8000000000000005
1.9000000000000006


#### We expect the output to be exact 0.1 , 0.2 , 0.3 , 0.4 , . . . 1.9 . But that is not the case which can be seen in the output

### **Reason**:
#### The main reason is that 0.1 cannot be exactly represented in binary ,its binary representation is a repeating fraction , which means that the binary representation is not finite , so in practice it is rounded off to some finite number of digits , which is reason for some of the rounding error which can be seen above . This limitation could affect computations involving floating point arthmetic

## QUESTION 3

### PART A
#### The values of x for which the given formula may lead to large round-off errors are large values , since for large values the values of $\sqrt{x+1}$  and $\sqrt{x}$ are nearly equal and subtraction of nearly equal numbers results in large round-off errors.
#### MODIFIED FORMULA :
$$ \dfrac{1}{\sqrt{x+1} + \sqrt{x}} $$

### PART B
#### The values of x for which the given formula may lead to large round-off error are values closer to 0 , since for values closer to 0 , the values $\ln{(x^2)}$ and $\ln{(x^2 + x)}$ are nearly equal and substraction of nearly equal numbers result in large rounf-off errors.
#### MODIFIED FORMULA :
$$ \ln{\dfrac{x}{1 + x}} $$

### PART C
#### The values of x for which the given formula may lead to large round-off errors are values closer to $\dfrac{\pi}{4}$ , since for such values of $cos^2(x)$  and $sin^2(x)$ are nearly equal i.e,1/2 and subtraction of nearly equal numbers results in large round-off errors.
#### MODIFIED FORMULA :
$$ cos(2x) $$

## QUESTION 4

In [4]:
# QUESTION 4

def make_my_size10(inp):
    inp = list(inp)
    length = len(inp)
    needed = 10 - length
    if(length >= 10):
        return inp[:10]
    else: 
        for i in range(needed):
           inp.append(0)
        return inp
            

print(make_my_size10(range(1,2)))
print(make_my_size10(range(1,15)))


[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


## QUESTION 5

In [5]:
# QUESTION 5

def my_make_size10(inp):
    zero = np.zeros(10,dtype=int)
    ans = np.append(inp,zero)
    return ans[:10]

print(list(my_make_size10(range(1,2))))
print(list(my_make_size10(range(1,15))))

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


## QUESTION 6

In [6]:
# QUESTION 6

input_array = np.random.choice(np.arange(10,101),size=50,replace=False)

vector = np.reshape(input_array,(50,1))

print("The column vector is :")

print(vector)

vector_flipped = np.flip(vector)

print("The column vector after flipping is :")

print(np.flip(vector))

The column vector is :
[[ 11]
 [ 86]
 [ 69]
 [ 85]
 [ 26]
 [ 47]
 [ 75]
 [ 70]
 [ 27]
 [ 81]
 [ 44]
 [ 80]
 [ 31]
 [ 54]
 [ 34]
 [ 53]
 [ 78]
 [ 61]
 [ 65]
 [ 12]
 [ 39]
 [ 32]
 [ 60]
 [ 14]
 [ 66]
 [ 99]
 [ 10]
 [ 21]
 [ 13]
 [ 17]
 [ 33]
 [100]
 [ 49]
 [ 92]
 [ 52]
 [ 55]
 [ 25]
 [ 22]
 [ 76]
 [ 37]
 [ 20]
 [ 30]
 [ 93]
 [ 46]
 [ 74]
 [ 91]
 [ 96]
 [ 97]
 [ 23]
 [ 98]]
The column vector after flipping is :
[[ 98]
 [ 23]
 [ 97]
 [ 96]
 [ 91]
 [ 74]
 [ 46]
 [ 93]
 [ 30]
 [ 20]
 [ 37]
 [ 76]
 [ 22]
 [ 25]
 [ 55]
 [ 52]
 [ 92]
 [ 49]
 [100]
 [ 33]
 [ 17]
 [ 13]
 [ 21]
 [ 10]
 [ 99]
 [ 66]
 [ 14]
 [ 60]
 [ 32]
 [ 39]
 [ 12]
 [ 65]
 [ 61]
 [ 78]
 [ 53]
 [ 34]
 [ 54]
 [ 31]
 [ 80]
 [ 44]
 [ 81]
 [ 27]
 [ 70]
 [ 75]
 [ 47]
 [ 26]
 [ 85]
 [ 69]
 [ 86]
 [ 11]]


## QUESTION 7

In [7]:
n = 400

def checkerboard(n):
    arr = np.zeros((n,n),dtype=int)
    for i in range(n):
        for j in range(n):
            arr[i][j] = (i+j)%2
    return arr

print("The checkerboard without tile function is :")
print(checkerboard(n))
print("Time taken is :")
%timeit checkerboard(n)

print("\n")

tile = np.array([
    [0,1],
    [1,0]
])

print("The checkerboard with tile function is :")
print(np.tile(tile,(int(n/2),int(n/2))))
print("Time taken is :")
%timeit np.tile(tile,(int(n/2),int(n/2)))


The checkerboard without tile function is :
[[0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 ...
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]]
Time taken is :
32.7 ms ± 119 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


The checkerboard with tile function is :
[[0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 ...
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]]
Time taken is :
425 µs ± 7.06 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## QUESTION 8

In [8]:
matrix = np.random.randint(low=-20,high=21,size=(10, 10))

print("The original matrix is : ")

print(matrix,end="\n\n")

maximum_value = np.max(matrix)

minimum_value = np.min(matrix)

if( maximum_value == minimum_value ):
    print("ERROR : The maximum value and minimum value of the matrix is same")
else :
    matrix = (matrix - minimum_value) / (maximum_value - minimum_value)

    print("The matrix after normalizing is : ")

    print(matrix)

The original matrix is : 
[[-17 -15  15 -15 -17  10 -13   9  11   4]
 [  5   5   8 -16 -19  12   2   5  -4  11]
 [ -7  -2  -9 -19   7  -5 -19 -20   3 -20]
 [ -2  -8  10  11   5  14 -13 -16 -16 -20]
 [ -7   7   7  -3 -15 -17   0  -1  12  11]
 [  9  20  10  -2 -14  16   6  17 -11  20]
 [  3 -11 -20  -2  -9 -15 -13  -2 -20 -19]
 [  4  -5  12  -9 -16  14 -17   9  -3  -5]
 [ -1 -13   3  12  10 -14  -3   7   3  -4]
 [ 19  12  18   3  -6   6  17  17 -18  15]]

The matrix after normalizing is : 
[[0.075 0.125 0.875 0.125 0.075 0.75  0.175 0.725 0.775 0.6  ]
 [0.625 0.625 0.7   0.1   0.025 0.8   0.55  0.625 0.4   0.775]
 [0.325 0.45  0.275 0.025 0.675 0.375 0.025 0.    0.575 0.   ]
 [0.45  0.3   0.75  0.775 0.625 0.85  0.175 0.1   0.1   0.   ]
 [0.325 0.675 0.675 0.425 0.125 0.075 0.5   0.475 0.8   0.775]
 [0.725 1.    0.75  0.45  0.15  0.9   0.65  0.925 0.225 1.   ]
 [0.575 0.225 0.    0.45  0.275 0.125 0.175 0.45  0.    0.025]
 [0.6   0.375 0.8   0.275 0.1   0.85  0.075 0.725 0.425 0.375]
 [0

## QUESTION 9

In [9]:
inp_array_1 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])

inp_array_2 = np.array([
    [5,2,3,4,5],
    [6,7,8,9,10],
    [11,29,15,14,10],
    [89,17,18,19,20],
    [21,22,13,24,25]
])

set1 = set(inp_array_1.ravel())
set2 = set(inp_array_2.ravel())

print(set1.intersection(set2))

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 17, 18, 19, 20}


## QUESTION 10

In [10]:
my_tuple = (0,1,2,3,'3',4,5,6,1.2,4.6,"srinith","harshith","srinivas","sridevi")

length_of_tuple = len(my_tuple)

def find_index_in_tuple(item):
    index = 0
    for value in my_tuple:
        if(value == item):
            print("The index of item in tuple 'my_tuple' is ",index)
            return index
        index = index + 1
    if index == length_of_tuple:
        print("ERROR : Item is not present in the input tuple")
    return index

# EXAMPLE OUTPUTS

# NOTE : This is 0 based indexing

indx = find_index_in_tuple(3)
indx = find_index_in_tuple('3')
indx = find_index_in_tuple(1.2)
indx = find_index_in_tuple('srinith')
indx = find_index_in_tuple('sridevi')
indx = find_index_in_tuple(9)

The index of item in tuple 'my_tuple' is  3
The index of item in tuple 'my_tuple' is  4
The index of item in tuple 'my_tuple' is  8
The index of item in tuple 'my_tuple' is  10
The index of item in tuple 'my_tuple' is  13
ERROR : Item is not present in the input tuple
