# Q. 1

In [42]:
import numpy as np

def last_element(x):
  sum1 = x[0]
  sum2 = x[0]
  for i in range(1, len(x)):
    if i == len(x)-1:
      sum1 = sum1 + x[i]
    else:
      sum2 = sum2 + x[i]
      sum1 = sum1 + x[i]
  return sum1-sum2

np.random.seed(5)

# Generating random arrays
for k in [5, 10, 50, 100, 1000, 10000]:
  x = np.random.rand(k)
  sum = last_element(x)
  # Printing the sum
  print("Roundoff error: ",abs(x[-1]-sum))

Roundoff error:  1.1102230246251565e-16
Roundoff error:  4.440892098500626e-16
Roundoff error:  1.2212453270876722e-15
Roundoff error:  6.661338147750939e-16
Roundoff error:  1.4432899320127035e-15
Roundoff error:  2.808864252301646e-14


# Q. 2


In [32]:
# The given algorithm is:

x = 0.0
while x < 2.0:
  print(x)
  x += 0.1

0.0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6
0.7
0.7999999999999999
0.8999999999999999
0.9999999999999999
1.0999999999999999
1.2
1.3
1.4000000000000001
1.5000000000000002
1.6000000000000003
1.7000000000000004
1.8000000000000005
1.9000000000000006


### Explanation of Output:

- As floating point numbers in computers are stored with a limited number of bits i.e., either 32/ 64 bits because of this we lead to finite precision.
- Due to this finite precision all decimal numbers cannot be exactly represented and repeated calculations can increase this small errors.
- In the above code like adding 0.1 can lead to accumulating representation errors.
- Each subsequent operation introduces its own error but also adds errors from previous iterations causing deviations from expected values.


# Q. 3

### A)
**Problem:** As $x$ becomes, the difference between $\sqrt{x+1}$ and $\sqrt{x}$ becomes very small leading to loss of significance in floating-point arithmetic.

**Fix:** Use the identity $\sqrt{x+1}^2-\sqrt{x}^2$, i.e, $\sqrt{x+1} - \sqrt{x} = \frac{1}{\sqrt{x+1}+\sqrt{x}}$. Doing this we can do correct arthmetic as this can lead to a correct potential loss of significance in floating-point arithmetic.

### B)
**Problem:** When $x$ is very close to zero the give expression evaluates to $-∞$ this can introduce large round-off errors.

**Fix:** Instead use logarithmic properties, $\log(x^2)-\log(x^2+x) = \log(\frac{x^2}{x^2+x})$.  Doing this we can do correct arthmetic as this can lead to a correct potential loss of significance in floating-point arithmetic as this method evaluates to value near to $0$.

### C)
**Problem:** In this expression the round-off error comes when $\sin^2(x)$ and $\cos^2(x)
$ are nearly same as their difference can lead to loss in precision.

**Fix:** Instead use $\cos(2x)$ formula for avoiding round-off errors.


# Q. 4


In [33]:
def my_make_size10(x):
  # If the length of x > 10, return the first 10 elements
  if len(x) > 10:
    return list(x)[:10]
  # If the length of x <= 10, padding with zeros to make its length 10
  else:
    return list(x) + [0] * (10 - len(x))

print(my_make_size10(range(1,3)))
print(my_make_size10(range(1,15)))

[1, 2, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# Q. 5

In [34]:
import numpy as np

def my_make_size10(x):
  x = np.array(x)
  truncated = x[:10]
  zeros_to_append = 10 - truncated.size
  # Using .append() to add zeros
  return list(np.append(truncated, [0] * zeros_to_append))

# Test the function
print(my_make_size10(range(1,2)))
print(my_make_size10(range(1,15)))

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]


# Q. 6

In [35]:
import numpy as np
import random

unique_integers = random.sample(range(10, 101), 50)

# Converting the list into a numpy column vector
vector = np.array(unique_integers).reshape(-1, 1)

# Reversing the column vector
reversed_vector = vector[::-1]

print("Original vector:")
print(vector)
print("\nReversed vector:")
print(reversed_vector)

Original vector:
[[ 72]
 [ 49]
 [ 86]
 [ 58]
 [ 39]
 [ 90]
 [ 24]
 [ 12]
 [ 52]
 [ 97]
 [ 63]
 [ 19]
 [ 64]
 [ 42]
 [ 21]
 [ 55]
 [ 14]
 [ 45]
 [ 43]
 [ 50]
 [ 25]
 [ 65]
 [ 66]
 [ 56]
 [ 17]
 [ 93]
 [ 92]
 [ 26]
 [ 75]
 [ 98]
 [ 60]
 [ 47]
 [100]
 [ 83]
 [ 67]
 [ 69]
 [ 53]
 [ 46]
 [ 68]
 [ 81]
 [ 23]
 [ 51]
 [ 82]
 [ 44]
 [ 36]
 [ 85]
 [ 32]
 [ 77]
 [ 57]
 [ 41]]

Reversed vector:
[[ 41]
 [ 57]
 [ 77]
 [ 32]
 [ 85]
 [ 36]
 [ 44]
 [ 82]
 [ 51]
 [ 23]
 [ 81]
 [ 68]
 [ 46]
 [ 53]
 [ 69]
 [ 67]
 [ 83]
 [100]
 [ 47]
 [ 60]
 [ 98]
 [ 75]
 [ 26]
 [ 92]
 [ 93]
 [ 17]
 [ 56]
 [ 66]
 [ 65]
 [ 25]
 [ 50]
 [ 43]
 [ 45]
 [ 14]
 [ 55]
 [ 21]
 [ 42]
 [ 64]
 [ 19]
 [ 63]
 [ 97]
 [ 52]
 [ 12]
 [ 24]
 [ 90]
 [ 39]
 [ 58]
 [ 86]
 [ 49]
 [ 72]]


# Q. 7

In [36]:
import numpy as np

def my_checkerboard(n):
    board_list = []
    for i in range(n):
        row = [(i + j) % 2 for j in range(n)]
        board_list.append(row)

    return np.array(board_list, dtype=int)

def inbuilt_checkerboard(n):
    pattern = np.array([[0, 1], [1, 0]])
    return np.tile(pattern, (n//2, n//2))

print("Time of execution for my_checkerboard for size of checkerboard = 100: ")
%timeit my_checkerboard(100)
print("Time of execution for inbuilt_checkerboard for size of checkerboard = 100: ")
%timeit inbuilt_checkerboard(100)

print("Time of execution for my_checkerboard for size of checkerboard = 150: ")
%timeit my_checkerboard(150)
print("Time of execution for inbuilt_checkerboard for size of checkerboard = 150: ")
%timeit inbuilt_checkerboard(150)


print("Time of execution for my_checkerboard for size of checkerboard = 200: ")
%timeit my_checkerboard(200)
print("Time of execution for inbuilt_checkerboard for size of checkerboard = 200: ")
%timeit inbuilt_checkerboard(200)

Time of execution for my_checkerboard for size of checkerboard = 100: 
1.31 ms ± 170 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Time of execution for inbuilt_checkerboard for size of checkerboard = 100: 
28.1 µs ± 794 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time of execution for my_checkerboard for size of checkerboard = 150: 
2.82 ms ± 90.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Time of execution for inbuilt_checkerboard for size of checkerboard = 150: 
52.2 µs ± 651 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time of execution for my_checkerboard for size of checkerboard = 200: 
6.7 ms ± 2.25 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
Time of execution for inbuilt_checkerboard for size of checkerboard = 200: 
87 µs ± 658 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Q. 8

In [37]:
import numpy as np

M = np.random.randint(-20, 21, size=(10, 10))

# Finding the min and max values in the matrix M
min_val = M.min()
max_val = M.max()

# Normalizing the matrix M
M_normalised = (M - min_val) / (max_val - min_val)

print("Original Matrix:")
print(M)
print("\nNormalized Matrix:")
print(M_normalised)

Original Matrix:
[[ -6 -12  16 -13  -9   6 -13  19   8  -4]
 [ -6  19 -12  17  17  -4   3  -1   9  -9]
 [-20 -16   7 -14   1  -7  -7  12  19  -7]
 [-15  19  18 -20  -4  -5   5  -5 -11  -1]
 [ 20   1  12  18 -18  17 -20  -5  10  -1]
 [-19 -15 -20  -6  14 -17 -14   4  -8  -7]
 [ 17   4   3  17  -4 -15  -3 -15   6 -13]
 [ 16 -17 -10  -1   0 -17  -9  16  18   7]
 [-18   2  -4  18  -8   5  -9 -19  -7   9]
 [  9 -13  14 -18  12  16  18  17 -17  12]]

Normalized Matrix:
[[0.35  0.2   0.9   0.175 0.275 0.65  0.175 0.975 0.7   0.4  ]
 [0.35  0.975 0.2   0.925 0.925 0.4   0.575 0.475 0.725 0.275]
 [0.    0.1   0.675 0.15  0.525 0.325 0.325 0.8   0.975 0.325]
 [0.125 0.975 0.95  0.    0.4   0.375 0.625 0.375 0.225 0.475]
 [1.    0.525 0.8   0.95  0.05  0.925 0.    0.375 0.75  0.475]
 [0.025 0.125 0.    0.35  0.85  0.075 0.15  0.6   0.3   0.325]
 [0.925 0.6   0.575 0.925 0.4   0.125 0.425 0.125 0.65  0.175]
 [0.9   0.075 0.25  0.475 0.5   0.075 0.275 0.9   0.95  0.675]
 [0.05  0.55  0.4   0.95  0.

# Q. 9

In [38]:
import numpy as np

# 2D numpy arrays
A = np.array([[10, 40, 10], [1, 2, 3]])
B = np.array([[1, 10, 30], [3, 100, 150]])

def common_values(arr1, arr2):
  s1 = set()
  s2 = set()

  for row in arr1:
      for value in row:
          s1.add(value)

  for row in arr2:
      for value in row:
          s2.add(value)

  # Finding common elements between the numpy arrays
  common_values = s1.intersection(s2)
  return list(common_values)

print("Common values between the 2D numpy arrays is: ",common_values(A,B))

Common values between the 2D numpy arrays is:  [1, 10, 3]




# Q. 10


In [39]:
def find(a,item):
  cnt = 0
  for i in a:
    if(i == item):
       return True, cnt
    cnt += 1
  return False, -1

# Defining a tuple
a = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
item = int(input("Enter the item you want to find the index of: "))
c,b = find(a,item)
if c:
  print(f"The index of {item} in the tuple is: {b}")
else :
  print(f"The item which you want to find doesn't exist")

Enter the item you want to find the index of: 3
The index of 3 in the tuple is: 2
